src/Codecool.CodecoolShop/Controllers/HomePageController.cs
using Codecool.CodecoolShop.Models;
using Codecool.CodecoolShop.Services.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Serilog;
using System.Collections.Generic;
using System.Diagnostics;

namespace Codecool.CodecoolShop.Controllers
{
    public class HomePageController : Controller
    {
        private readonly IProductServices _productService;
        private readonly ICategoryService _categoryService;
        private readonly ISupplierService _supplierService;

        public HomePageController(IProductServices productServices,
            ICategoryService categoryService, ISupplierService supplierService)
        {
            _productService = productServices;
            _categoryService = categoryService;
            _supplierService = supplierService;
        }

        public IActionResult Index(int category = 0, int supplier = 0)
        {
            Log.Information("User is on the main page");

            IEnumerable<DataAccessLayer.Model.Category> categories = _categoryService.GetCategories();
            IEnumerable<DataAccessLayer.Model.Supplier> suppliers = _supplierService.GetSuppliers();
            IEnumerable<DataAccessLayer.Model.Product> products = _productService.GetSortedProducts(category, supplier);

            HomeViewModel viewModel = new(categories, suppliers, products, category, supplier);

            return View(viewModel);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Codecool.CodecoolShop/Views/HomePage/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model HomeViewModel

<form asp-area="" asp-controller="HomePage" asp-action="Index">
    <div class="sort-control-group">
        <div class="sort-control-item">
            <label for="sort_by_category">Sort by Category:</label>
            <select name="category">
                @if (Model.CurrentCategory == 0)
                {
                    <option value="0" selected>All</option>
                }
                else
                {
                    <option value="0">All</option>
                }
                @foreach (var category in Model.Categories)
                {
                    @if (Model.CurrentCategory == category.Id)
                    {
                        <option value="@category.Id" selected>@category.Name</option>
                    }
                    else
                    {
                        <option value="@category.Id">@category.Name</option>
                    }
                }
            </select>
        </div>
        <div class="sort-control-item">
            <label for="sort_by_suppliers">Sort by Suppliers:</label>
            <select name="supplier">
                @if (Model.CurrentSupplier == 0)
                {
                    <option value="0" selected>All</option>
                }
                else
                {
                    <option value="0">All</option>
                }
                @foreach (var supplier in Model.Suppliers)
                {
                    @if (Model.CurrentSupplier == supplier.Id)
                    {
                        <option value="@supplier.Id" selected>@supplier.Name</option>
                    }
                    else
                    {
                        <option value="@supplier.Id">@supplier.Name</option>
                    }
                }
            </select>
        </div>

        <button name="sort" type="submit">Sort</button>
    </div>
</form>

<div class="container">


    <div class="cards">
        @foreach (var element in Model.Products)
        {
            <div class="card">
                <img src="img/@(element.Name).jpg">

                <div class="card-body">
                    <h5 class="card-title">@element.Name</h5>
                    <p class="card-text"><strong>Price: @element.Price.ToString("C2")</strong></p>
                    <a href="" id="add-to-cart" data-product-id="@element.Id" data-product-name="@element.Name" type="button"
                       data-price="@element.Price" class="btn btn-primary">
                        Add To Cart
                    </a>
                </div>
            </div>
        }
    </div>

</div>